### ISSUE TITLE
Which docker-perl has uselongdouble=define or active?

### ISSUE THREAD

**Issue by gk7279** [Perl/docker-perl#106]
Hi perl team-

Here is the output of my perl -V

`perl -V
Summary of my perl5 (revision 5 version 34 subversion 0) configuration:
   
  Platform:
    osname=linux
    osvers=4.19.0-14-cloud-amd64
    archname=x86_64-linux-gnu
    uname='linux cd6dd096362f 4.19.0-14-cloud-amd64 #1 smp debian 4.19.171-2 (2021-01-30) x86_64 gnulinux '
    config_args='-Darchname=x86_64-linux-gnu -Duse64bitall -Duseshrplib -Dvendorprefix=/usr/local -des'
    hint=recommended
    useposix=true
    d_sigaction=define
    useithreads=undef
    usemultiplicity=undef
    use64bitint=define
    use64bitall=define
    uselongdouble=undef`

The error I am seeing is `Double size is not compatible at /usr/local/lib/perl5/5.34.0/x86_64-linux-gnu/Storable.pm line 421,`

I was wondering if you can point me to a docker-perl version where it has the uselongdouble defined. Thanks.

**Comment by zakame** [comment]
Hi @gk7279, thanks for the query!

We don't have any Docker Hub build of `perl` that has `-Duselongdouble` explicitly defined, so you may have to put this in yourself in a custom image build, such as in this line for the `perl:5.34` Dockerfile https://github.com/Perl/docker-perl/blob/311f05366d91427d289740dd15fb9401dc4347ef/5.034.000-main-buster/Dockerfile#L16

Be forewarned however that defining `uselongdouble` may cause building or testing  of other CPAN modules to fail - may I ask what's the use case for needing `Storable` in the first place?

**Comment by gk7279** [comment]
Thanks @zakame !

Our Bioinfo uses that module. I got it to work. Thanks.
