### ISSUE TITLE
linux-libc-dev version in debian based images is out of date and contains multiple high risk CVEs

### ISSUE THREAD

**Issue by jonisno** [Perl/docker-perl#108]
Could a new build be done with an updated debian base image?

**Comment by zakame** [comment]
Hi @jonisno, thanks for the report!

See #105 - we should be due a rebuild of the `perl` images as soon as the `buildpack-deps` and `debian` images get the patched `linux-libc-dev`.

**Comment by zakame** [comment]
I'll also quote myself in https://github.com/Perl/docker-perl/issues/105#issuecomment-853829815, the relevant being (and with emphasis:)

>we'd encourage image users to do this `apt-get upgrade` step on their own derived image creations, as they would usually be in a better position to both find updated security packages as well as _ensure that they comply to their own security requirements_ beyond Docker image scanning

**Comment by jonisno** [comment]
Hey @zakame, thanks for the reply. It also strikes me that I'm quite a numpty not even to have thought of upgrading the image myself! Will close this now :)
