### ISSUE TITLE
more historical versions?

### ISSUE THREAD

**Issue by dagolden** [Perl/docker-perl#11]
It would be very handy to have more versions of perl available for testing on legacy perls.  What do you think about making that part of the official repo vs having it rolled somewhere else?

**Comment by zakame** [comment]
:+1: 

FWIW I maintain a fork of this with 5.14.2 (primarily for my $WORK needs): https://registry.hub.docker.com/u/zakame/perl/

**Comment by tianon** [comment]
Are the older versions still supported upstream? (security backports, etc)

**Comment by dagolden** [comment]
No.  The latest two Perls are generally supported.  The one older than that is supported for security backports only.  Currently, that's 5.20.x and 5.18.x supported, with 5.16.x getting security fixes only.

In a few months, when 5.22 ships, then it will be 5.22.x and 5.20.x supported and 5.18.x getting security fixes only.

Nonetheless, people still run vastly older versions and I'd like to have them available for testing CPAN modules on a clean build of antique Perls.  But if making them "official" mis-sets support expectations, then I can always publish them privately.

**Comment by yosifkit** [comment]
It's up to @PeterMartini, but it would be fine on my end to do a PR to "add old releases" to the official-images repo then do another PR to remove them once they are pushed to the hub.  The images would stay there "unsupported" and not be updated with any base image changes, but they would be available for people to use.

**Comment by zakame** [comment]
Might be a bit extra burden for the maintainer.  I considered that initially, but opted to just fork and maintain the version I use by myself.

**Comment by PeterMartini** [comment]
@dagolden How far back do you think we should go?

**Comment by dagolden** [comment]
@PeterMartini for me, personally, I'd love every non-dev release from 5.8.1 onwards, but that's because I do some wacky toolchain stuff where testing on stock 5.x.y for arbitrary x.y is actually interesting.

But for the general public, I could imagine having every latest point release from 5.8 on onwards could be of interest.  E.g. 5.8.9, 5.10.1, 5.12.5, etc.

**Comment by PeterMartini** [comment]
@zakame - it looks like your fork changed to use wheezy, is that a requirement or was that just to get it to build?

**Comment by zakame** [comment]
@PeterMartini yep, jessie doesn't build 5.14.2 now due to the newer gcc, etc. and I have not much time to investigate further.

**Comment by zakame** [comment]
Just for the record, I re-run my build with jessie and here's my problem:

```
# Failed at ../lib/h2ph.t line 49
#      got 'Illegal declaration of subroutine main::__has_include at _h2ph_pre.ph line 488.
# '
# expected /(?^:syntax OK$)/
# Failed at ../lib/h2ph.t line 56
#      got "Illegal character in prototype for main::__has_include : STR at _h2ph_pre.ph line 488.\nCompilation failed in require at lib/h2ph.pht line 1.\nCompilation failed in require at -e line 1.\n"
# expected ""
../lib/h2ph.t .....................................................
Failed 2/6 subtests
```

**Comment by PeterMartini** [comment]
Sorry this is taking so long.

For 5.16, I've found that the Configure specific commit 6f87f404fa51739971a4068da1f11443024f3fc4 from later Perl versions applies cleanly and allows 5.16 to finish building with no other changes.

I've also been tripped up by dist/IO/t/io_unix.t failing in 5.16.x, and maybe even the versions that are still actively supported, if TEST_JOBS is too high.  Single test instance always passes, but it fails increasingly often as I bump the number (and its worth noting that because those jobs are IO bound, I can see speed gains much higher than $(nprocs)).

I've gotten back to 5.12 working just with that Configure patch, and am *almost* done with 5.10 now - I had to cherry pick a patch for hints/linux.sh, 40f026236b9959b7ad3260fedc6c66cd30bb7abc, so that Configure could find the libraries and build properly, and I'm still getting a small number of test failures that will take a little more time to debug.

Once that's done, I'm hoping 5.8.9 is straightforward.

**Comment by PeterMartini** [comment]
'master' here currently builds back to 5.12, and the versions that have patches also have patchlevel.h patched to include references to the changes necessary to get them to build.

**Comment by PeterMartini** [comment]
@zakame - I'm not sure if you saw my last two updates, but I've got 5.14.4 in this repo building cleanly on the same base as 5.20, I just had to cherry pick a Configure patch to do so.  Does that suit your needs?

**Comment by dagolden** [comment]
Are you hand patching? What about using Devel::Patchperl?

**Comment by PeterMartini** [comment]
Hand patching; I didn't know about Devel::Patchperl, though now I'll take a look!  What does it bring to the table here?

**Comment by dagolden** [comment]
[Devel::PatchPerl](https://metacpan.org/pod/Devel::PatchPerl) is a program to patch historical perls to get them to build on modern systems.  It *doesn't* patch the tests, though, some older perls will still fail tests (but generally work).  It's used by perlbrew and plenv for building perls in those systems.

Essentially, it's the compiled wisdom of people doing exactly what you're doing by hand.  For security reasons, you probably should freeze a copy of it into this repo.

**Comment by zakame** [comment]
@PeterMartini oh nice, that's great :+1: though $WORK is still strictly 5.14.2, I'll try to get the ball rolling here to use 5.14.4.

@dagolden oh yeah, forgot about Devel::PatchPerl!  I wonder though if we ought to be using perlbrew or plenv here anyway as they already handle the hard problem of building perls.

**Comment by PeterMartini** [comment]
I just got the Devel::PatchPerl piece tested out last night, and that makes this easy enough I'll add definitions here for all the patch levels back to 5.8.0, for reference if not library inclusion

**Comment by dagolden** [comment]
I wouldn't use either.  I think we want as little as possible in the images.

**Comment by PeterMartini** [comment]
@dagolden Btw, I very much want to get this sorted before the NY Perl Hackathon so we can use it as a base for other projects :-)

**Comment by dagolden** [comment]
I'm at the Perl QA Hackathon in Berlin currently, and Matthew Horsfall is
here and will be working on Devel::PatchPerl, so this is a good time to
experiment and raise issues, since there are round-tuits available.

David

**Comment by PeterMartini** [comment]
I have a branch here, https://github.com/perl/docker-perl/tree/devel-patchperl, using Devel::PatchPerl to generate a patch to be run against the downloaded source.  It doesn't appear to have pulled in the (pretty trivial) patch needed for 5.16 and earlier to pass the one failing test (h2ph), 6f87f404fa51739971a4068da1f11443024f3fc4

**Comment by dagolden** [comment]
PatchPerl docs say it doesn't try to make things pass tests -- just get it building, but I think some test patches have been put in.  You might be able to contribute it.

**Comment by PeterMartini** [comment]
If I don't get to this by Saturday, I added it to https://github.com/nyperlmongers/nyperlhackathon2015/wiki/Docker-Perl-Hacking to recruit others to help me :grinning:

**Comment by zakame** [comment]
Perhaps related to my other ticket #13 we could build a variant that builds any perl versions that the user wants, e.g. `docker run -it perl:buildperl 5.14.2` would make a local image for 5.14.2...

**Comment by PeterMartini** [comment]
@xdg - We've got back to 5.8.9 in the official-images now, woot!  And have a framework in place for extending to as many other versions as desired.

@yosifkit - Should I do another PR now to remove all but the two supported (5.18 and 5.20?)  Once you're satisfied, I'll close this issue.

@zakame - I'm interested in the ONBUILD thing and will follow up in the other issue, though not sure of best practices for it.

FWIW, I'm happy to maintain (via Devel::PatchPerl) as far back as we'd like, though we'll only be putting the p5p maintained versions in the official-images repo.

**Comment by yosifkit** [comment]
Sure!  Since you just wanted those available and not as "supported" versions, that would be fantastic to drop them out of the library file, which will drop them off the "supported versions" list in the description on the docker hub.  Just in case users don't look at the tags page on the hub, you may want to let users know that older versions are available for those that need it, but they are "unsupported".

**Comment by PeterMartini** [comment]
Resolving; 5.22.0 is now in as well, and the older versions (back to 5.8.9) are still available.

I'm perfectly happy to add more versions as pull requests if someone wants to do so; otherwise, I'll get to them when I'm a bit less crunched at $work.

**Comment by mkszuba** [comment]
Sorry about severe thread necromancy but this seems to be the very same matter, moreover it would feel wasteful to to open a new issue for such an old version of Perl. Anyway, following the discussion in https://github.com/Perl/docker-perl/issues/70 I have attempted to locally rebuild _5.014.004-main-jessie_, using the master branch of this repository as of about a week ago - and got exactly the same result as Zak in https://github.com/Perl/docker-perl/issues/11#issuecomment-89918827 above. Could it be that this has regressed?

**Comment by Tekki** [comment]
@mkszuba I wonder if this Perl installation is really broken or not.
Tried the following: commented out
`&& make test_harness \`
in the Dockerfile, built the image, started a container, ran `cpanm Mojo::mysql` that installs 29 modules and everything was fine.

**Comment by zakame** [comment]
Hi @mkszuba, no worries about the issue necro.

You can try dropping https://github.com/Perl/perl5/commit/6f87f404fa51739971a4068da1f11443024f3fc4.patch into the `5.014.004-main-jessie` directory, which the `docker build` should pick up as a second patch to add along with what `Devel::PatchPerl` provides.  As noted earlier in this thread, PatchPerl doesn't normally carry patches to make tests pass, so it might be worthwhile for you to keep the above patch in your own fork of the repo for perl-5.14.

(That aside, it might be worth exploring a way to keep custom patches around somehow, as `generate.pl` currently wipes everything away to regenerate files.)

**Comment by mkszuba** [comment]
Ah, so these tests were not meant to pass after all; having seen them mentioned in this thread I assumed the relevant patch had been included into this repository at some point. All is well (or even better than well, as I can now get Gitlab CI to build 5.14.4 images not only against Jessie but against Buster as well) now, cheers!

**Comment by Tekki** [comment]
> Ah, so these tests were not meant to pass after all
The test target is called in the Dockerfile, so they are meant to pass. But as @zakame said, we only apply the patches provided by `Devel::PatchPerl` to the source code and therefore should look for a way to add additional patches.
