### ISSUE TITLE
please provide a latest-dev version

### ISSUE THREAD

**Issue by rjbs** [Perl/docker-perl#125]
For automated testing against the latest development version of perl, it would be terrific to have either:

1. the latest v5.[odd].x development release; these are released on the 20th of every month
2. a nightly-ish build from the blead branch of perl5.git

Possibly there is some reason this is not easy, I don't know!  But thanks for all your work so far.

**Comment by zakame** [comment]
Hey @rjbs, thanks for the issue!  Let's see how we can get this sorted.

Option 1 is probably doable - we can probably watch https://github.com/Perl/perl5/tags for latest dev release and build when that happens. Option 2 however [might not be easy](https://github.com/docker-library/faq#can-i-use-a-bot-to-make-my-image-update-prs) for the image builders though.

**Comment by waterkip** [comment]
Perhaps we can do something with github actions and use a seperate docker hub location? We can perhaps add #60 in there as well. Perhaps call it: docker/perl-devel which includes images with the debug, nightly and development releases?

**Comment by rjbs** [comment]
Really, just getting the monthly build would be great.  In doing that, I'd hope we could get a "latest-blead" label, so I could have my actions track that.  My take is:

* monthly (blead release) would be _huge_
* anything more than that is nice and I'd use it, but not as big a deal

So if you did weekly, or every 10d?  Cool, I'd use it.  But the blead releases are bigger.

Thanks so much!

**Comment by zakame** [comment]
So to start, I'll merge #126 in soon and update https://github.com/docker-library/official-images/blob/master/library/perl to add the `latest-blead`/`devel` tag so we can get `docker run perl:latest-blead` up sooner. 💪 Next up is automating the process so that we'd have monthly PRs here for updating that tag against the newest blead - this can serve as a base for further getting debug/nightlies out on another registry, probably here on GitHub container registry.

**Comment by rjbs** [comment]
This is really exciting, thanks!

**Comment by zakame** [comment]
Hi @rjbs! We're running into an issue for naming `perl:latest-blead` in the Hub, cf https://github.com/docker-library/official-images/actions/runs/3972685927/jobs/6810812068

Would the alternative `perl:blead` and `perl:devel` tags work for you instead?

**Comment by zakame** [comment]
I went ahead and set `blead` and `devel` tags for now in [docker-library/official-images@`b0595a2` (#13928)](https://github.com/docker-library/official-images/pull/13928/commits/b0595a25cb0bca8a07c8ae25c4681f4bbecbd3e3#diff-40ed9e38417ffb2e97e136f9de487c6cdb45a2c5c1f8667b871cb8573b12f4a1R103) but let me know if you have other preferences 🙏

**Comment by rjbs** [comment]
I am definitely not worried too much about the specific names!

**Comment by zakame** [comment]
`perl:devel` images are now available and published on the Docker Hub, thanks everyone!

![image](https://user-images.githubusercontent.com/110625/214469418-6d45081e-3c68-4eec-b62a-f00a0fa23359.png)

`perl:stable` images (aliased to the current `perl:latest` release) are also available.

Documentation on https://github.com/docker-library/docs/tree/master/perl and automation work for the next dev release to follow soon.

**Comment by rjbs** [comment]
Thank you very much!
