### ISSUE TITLE
`onbuild` variant

### ISSUE THREAD

**Issue by zakame** [Perl/docker-perl#13]
Several language/toolchain images now have an `onbuild` variant to help jumpstart derivative images.  Might be useful here for Perl especially as the base Perl images are relatively larger than others.

Particular examples might be web framework images derived from this image, which in turn might also use `onbuild` for the user's own custom app images.

**Comment by afirth** [comment]
https://github.com/GrahamDumpleton/mod_wsgi-docker does a good job if anyone is looking for a starting point

**Comment by zakame** [comment]
On a related note, Docker 17.05 now supports [multi-stage builds][0]

[0]: https://docs.docker.com/engine/userguide/eng-image/multistage-build/

**Comment by tianon** [comment]
Probably worth doing a read through https://github.com/docker-library/official-images/issues/2076 -- most images `onbuild` variants are now officially deprecated, because the flexibility/usability of them just cannot meet a simple `Dockerfile` example in the image documentation.

**Comment by zakame** [comment]
@tianon sounds good, I too prefer documenting how to make images with `ONBUILD` instead of providing a variant.

**Comment by zakame** [comment]
https://github.com/docker-library/docs/pull/968 just got accepted, thanks @yosifkit @tianon!

I will close this once I confirm seeing the updated docs on the Hub.
