### ISSUE TITLE
Prep for Debian bookworm and 5.38

### ISSUE THREAD

**Issue by zakame** [Perl/docker-perl#135]
- https://www.debian.org/News/2023/20230610
- http://nntp.perl.org/group/perl.perl5.porters/266489

We'll likely go ahead and switch to bookworm/bullseye on the supported versions now (and keep bullseye/buster for the rest) while we await the 5.38.0 release later this month.

**Comment by zakame** [comment]
According to https://wiki.debian.org/DebianReleases `buster` received its final update and thus already EOL since [2022-09-10](https://www.debian.org/News/2022/20220910).  We generally follow the policy of docker-library when the selection of Debian base is involved, see e.g. https://github.com/Perl/docker-perl/issues/88 and https://github.com/docker-library/official-images/pull/8405 - in particular, we won't be able to do builds on Debian LTS (post-EOL) releases as the docker-library base only up to the last point release (e.g. https://github.com/docker-library/official-images/pull/14832.)  cc @tianon as he would know better than me 🙏 

For now though, we could do a 5.38.0/5.36.1 release on bookworm/bullseye/buster then switch to bookwork/bullseye only when 5.38.1 arrives - let me know if that works for you @AnaTofuZ 🙏

**Comment by tianon** [comment]
We usually try to avoid supporting more than two releases of a given distribution per version for things that are on the heavier side to build (esp. building from source), like Python, Ruby, etc. :grimacing:

The Debian Buster base images will still be maintained/updated through the LTS period though (but specifically _not_ ELTS, so until ~2024-06-30, and the limited set of supported LTS architectures will be reflected in the updated images), and we'll support you if you feel strongly that you really _should_ continue building/supporting Debian Buster-based images (and would just ask that you limit that set to what's really necessary/important).

**Comment by zakame** [comment]
Perl 5.38.0 now on Docker Hub 🎉
