### ISSUE TITLE
perldevel 5.39.1 import() issue

### ISSUE THREAD

**Issue by zakame** [Perl/docker-perl#138]
We can't build for 5.39.1 as `cpanm` is prevented from fully installing by a change in how perl behaves:
- https://metacpan.org/release/SHAY/perl-5.39.1/view/pod/perldelta.pod#Calling-the-import-method-of-an-unknown-package-produces-an-error
- https://github.com/Perl/perl5/issues/21269
- https://github.com/miyagawa/cpanminus/issues/662

So either we patch `cpanm` or await for 5.39.2... leaning towards the latter.

**Comment by miyagawa** [comment]
Should be fixed with App-cpanminus-1.7047.
