### ISSUE TITLE
Namespace the maintainer label

### ISSUE THREAD

**Issue by jberger** [Perl/docker-perl#150]
This is only a mild complaint, but as labels are inherited from base images, I've just noticed that all my work images have you fine folks in the labels as maintainer. Now I know where that comes from because I recognize your names, however, others might now and it could be confusing. Yes I can (and will start) to overload the "maintainer" label by hand, however, many (and probably most) people using say github actions, use automation to derive the labels for images from available metadata; see https://github.com/docker/metadata-action for example.

The solution I propose is to namespace your maintainer label with something that will be unambiguous. There exists a standard (such as it is) from the opencontainer initiative; see https://github.com/opencontainers/image-spec/blob/main/annotations.md . These are the types of label generated by the metadata action linked above. As such I would propose that you change your label from `maintainer` to `org.perl.image.maintainer` or something of that nature.

**Comment by tianon** [comment]
Another solid option would be just removing the `LABEL` entirely :eyes: :innocent:

**Comment by zakame** [comment]
Hi @jberger @tianon , thanks for this report! 👍 

Yeah I'm partial to just removing the `LABEL maintainer` entirely - the only time I've touched that label is when I added myself and forgot about it 😅 We can reintroduce as opencontainers annotations later, but for now there seem's no need.

**Comment by zakame** [comment]
Label dropped - will see this change in the docker-library release for next year's `perldevel` version or stable update 💪 Thanks!

**Comment by zakame** [comment]
Happy New Year! 🎉 This is now live in today's [5.39.6 update](https://github.com/docker-library/official-images/pull/15982) (and should also be in the older supported versions,) among other updates.  Enjoy!
