### ISSUE TITLE
Mounting a volume perl doesn't see pl file

### ISSUE THREAD

**Issue by snoopy86** [Perl/docker-perl#19]
Hi,

i want to run one pl script & wan't to mount volume from container to have access to folder with the script. When i put the script to the folder and run the docker it gives me error (Cannot open Perl script ... no such file or directory).

Dockerfile is this: https://github.com/snoopy86/siemens

Can you help please.

Tnx.

**Comment by yosifkit** [comment]
You are not using the perl image, but it should be similar.  You just need to mount the perl file.

```
docker run -it --rm -v /home/user/sendData/:/scripts/ perl cpan WWW::PushBullet && perl /scripts/sendDataEmoncms.pl

**Comment by PeterMartini** [comment]
Thanks @yosifkit !

@snoopy86 - does that answer your question?

**Comment by snoopy86** [comment]
Yes i have done it like that and now it works. 

Thanks @yosifkit !
