### ISSUE TITLE
'apt-get update' fail

### ISSUE THREAD

**Issue by dwburke** [Perl/docker-perl#25]
When trying to "apt-get update" in my Dockerfile it fails with 

 ---> Running in f3c1657f3351
E: The method driver /usr/lib/apt/methods/https could not be found.

I've tried 5.20, 5.22 and 5.24 tags

**Comment by zakame** [comment]
Hi @dwburke, is this still occuring?  I could not reproduce it in `perl:latest` tag (which pulls in `perl:5.24`):

```
#+BEGIN_SRC sh :results output
docker run --rm perl:latest /usr/bin/apt-get update
#+END_SRC

#+RESULTS:
#+begin_example
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://security.debian.org jessie/updates/main amd64 Packages [391 kB]
Ign http://httpredir.debian.org jessie InRelease
Get:3 http://httpredir.debian.org jessie-updates InRelease [142 kB]
Get:4 http://httpredir.debian.org jessie Release.gpg [2373 B]
Get:5 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
Get:6 http://httpredir.debian.org jessie Release [148 kB]
Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9064 kB]
Fetched 9829 kB in 31s (316 kB/s)
Reading package lists...
#+end_example
```

Have you made changes/updated `/etc/apt/sources.list` prior to the `apt-get update`?

**Comment by dwburke** [comment]
I just re-checked, the problem seems to have gone away.  I'll reopen the issue if I see it again.
