### ISSUE TITLE
5.26 is released!

### ISSUE THREAD

**Issue by JRaspass** [Perl/docker-perl#29]
Can we get the docker image updated with new tags?

https://metacpan.org/release/XSAWYERX/perl-5.26.0

**Comment by zakame** [comment]
Great!  Will prepare a new image now 👍

**Comment by robkinyon** [comment]
When do you expect the 5.26 image to be available?

**Comment by zakame** [comment]
Let me try pinging @PeterMartini, @rjbs, and @xsawyerx, once more :joy_cat:

**Comment by zakame** [comment]
@robkinyon if it is an option for you now, you can build `perl:5.26` from my branch https://github.com/zakame/docker-perl/tree/perl-5.26 .  I might try to push also on Docker Hub under `zakame/perl:5.26`.

**Comment by zakame** [comment]
For those who can't wait, I've added an automated build for `zakame/perl:5.26` on my Docker Hub repo https://hub.docker.com/r/zakame/perl/tags/

**Comment by zakame** [comment]
Thanks to @xsawyerx for the assistance! :tada:

**Comment by zakame** [comment]
`perl:5.26` is now up at the Docker Hub https://hub.docker.com/r/library/perl/

Enjoy!
