### ISSUE TITLE
support arm64 architecture

### ISSUE THREAD

**Issue by longquan7** [Perl/docker-perl#37]
I build the docker-perl/5.026.000-64bit/Dockerfile from arm64v8/buildpack-deps:stretch and make success,
so I think we can add it to support arm64.

**Comment by zakame** [comment]
Hi @longquan7 , thanks for the report!

I'll take a look into adding arm64 very soon.  Could I ask you to give us a PR to get it done sooner? :)

**Comment by longquan7** [comment]
@zakame ok, I will give you a PR

**Comment by zakame** [comment]
@longquan7 pleased to inform you and all that `arm64v8/perl` is now available: https://hub.docker.com/r/arm64v8/perl/

Let me know if there are issues and/or improvements.  Thanks!

**Comment by longquan7** [comment]
@zakame OK, Thanks!
