### ISSUE TITLE
Issues with cdn-fastly.deb.debian.org

### ISSUE THREAD

**Issue by samypr100** [Perl/docker-perl#42]
Hello,

I was using perl 5.24, but from version 5.24.1 to 5.24.2 the apt repo changed from where packages were downloaded from `http://deb.debian.org/debian/` to `http://cdn-fastly.deb.debian.org/debian/`. This change is causing certain packages to not be available. For example `libmysqlclient-dev` I'm getting the following error on 5.24.2:
```
E: Package 'libmysqlclient-dev' has no installation candidate
```
This worked on 5.24.1.

**Comment by tianon** [comment]
This is more likely due to the switch from `jessie` to `stretch` -- you likely want to install `default-libmysqlclient-dev`, since `libmysqlclient-dev` doesn't exist in stretch (and is provided by MariaDB instead).

**Comment by tianon** [comment]
(see https://lists.debian.org/debian-devel-announce/2016/09/msg00000.html for more details from the Debian maintainers)

**Comment by samypr100** [comment]
I see, I didn't notice this change for 5.24. Thanks for the clarification of the switch!

**Comment by zakame** [comment]
Hi @samypr100 , thanks for report!

I take that you have done an `apt-get upgrade` prior to installing?  @tianon is correct that Stretch changed MySQL packages, see https://www.debian.org/releases/stretch/amd64/release-notes/ch-whats-new.en.html#mariadb-replaces-mysql

**Comment by samypr100** [comment]
This is one of those things that an update on upstreams breaks things.

It's probably due to `buildpack-deps:latest` dependency on the perl Dockerfile that introduced the condition. I'm glad I didn't  decided to update the container in the production system :)

Maybe as a recommendation using a tag on `buildpack-deps` like `buildpack-deps:jessie` might have prevented this.

**Comment by tianon** [comment]
Indeed, see https://github.com/Perl/docker-perl/pull/35 which did exactly that. :smile: :+1:

**Comment by zakame** [comment]
Yep #35 is on the pipeline, I'll be requesting an image update this weekend (just finalizing some other tasks) :+1:

**Comment by samypr100** [comment]
Thanks!

**Comment by zakame** [comment]
Image update now queued https://github.com/docker-library/official-images/pull/3373
