### ISSUE TITLE
Upgrade upstream libraries

### ISSUE THREAD

**Issue by JJ** [Perl/docker-perl#46]
To avoid this kind of vulnerabilities https://hub.docker.com/r/_/perl/

**Comment by JJ** [comment]
Most of them are not really that important https://github.com/docker-library/buildpack-deps/issues/46

**Comment by zakame** [comment]
The Perl image is updated and will be rebuilt (perhaps twice, as the base image has indicated that it will update this weekend too.)  This will upgrade some libraries and perhaps reduce the vulns scanned later.

Also, as indicated before in #47, end-users of the Perl image are free to do their own full update of the image/container, should they require it.  Thanks!
