### ISSUE TITLE
Use HTTPS to fetch App-cpanminus

### ISSUE THREAD

**Issue by J0WI** [Perl/docker-perl#55]
These should be updated to use HTTPS.
I'm sorry that I can't provide a PR myself, `generate.pl` was always messing with my local Git config.
https://github.com/Perl/docker-perl/blob/0cb4fc3643d3d9b22026d93905dc9ca192cc7b0e/generate.pl#L85-L88

**Comment by zakame** [comment]
Thanks @J0WI!  I've already regenerated the Dockerfiles; they'll be updated in the Docker Hub on the next release.
