### ISSUE TITLE
Vulnerability reports from docker.com

### ISSUE THREAD

**Issue by gugod** [Perl/docker-perl#57]
https://hub.docker.com/r/library/perl/tags/

It looks like docker.com system is actively scanning for the uses of debian packages with known vulneralbility. It effects all perl images (clicking on the tag name will revealing the package names as well as a bunch of useful details.)

It looks a full rebuild is required.

**Comment by zakame** [comment]
Thanks @gugod for the report!

I think the official-images do weekly rebuilds, but seems to have stopped now (just checking your link says the last was 23 days ago;) @tianon would you know more?

I also recall that this would also mean that the base `buildpack-deps` needs a rebuild to pull in fixes, which can then be used during the perl build along with any patches than Devel::PatchPerl applies; I'll need to review if I need to pull in individual CVE fixes as well, as IIRC Devel::PatchPerl only applies patches for building perl...

**Comment by zakame** [comment]
I'm also due for an image update for Perl 5.28.1 and 5.26.3; it is easy enough, but let me await an updated scan for `buildpack-deps` and `debian:slim`...

**Comment by tianon** [comment]
See https://github.com/debuerreotype/docker-debian-artifacts/issues/56 for
some relevant discussion on this same topic.

**Comment by zakame** [comment]
Thanks @tianon!  Seems I can proceed with the 5.26.3/5.28.1 update here then, with 5.24.4 patch to follow.

**Comment by zakame** [comment]
5.28.1 and 5.26.3 images are now built and up on hub, thanks everyone!
