### ISSUE TITLE
Switch Perl 5.30 to Buster?

### ISSUE THREAD

**Issue by Tekki** [Perl/docker-perl#66]
Now that buildpack-deps:stable have moved to Buster, shall we switch to Buster in Perl 5.30?

**Comment by zakame** [comment]
Based on other langs they've started having `-buster` and `-stretch` variant images as well (on top of our existing `-threaded` and `-slim`,) so if we're following suit, we'll have to adjust `generate.pl` a bit.

**Comment by Tekki** [comment]
At the moment Perl 5.8-18 are based on Jessie and 20-30 on Stretch. If we want Buster and Stretch variants for all versions this will probably need a little bit more than just a bit.
If we are going in this direction please close this issue.

**Comment by zakame** [comment]
Not all versions needs multi Debian dist support, only the current 5.30 and 5.28, per [perlpolicy](https://metacpan.org/pod/distribution/perl/pod/perlpolicy.pod#MAINTENANCE-AND-SUPPORT).  Folks can freely adapt the Dockerfiles for older releases if they need it.

We can probably expand the [`debian_release`](https://github.com/Perl/docker-perl/blob/92233bc5293c2eb17f3019f329cc67fd96d92bcf/generate.pl#L234-L241) option to take an array of releases aside of just a single item; I'll take a stab at this tomorrow.

Thanks @Tekki for the suggestion!
