### ISSUE TITLE
Update old images on Docker Hub to schema 2

### ISSUE THREAD

**Issue by mkszuba** [Perl/docker-perl#70]
I use Perl images from Docker Hub for CI purposes, using GitLab-CI, in one of my projects. We run tests for a few different Perl version but the oldest one we support is 5.14. Recently I attempted to speed CI builds up by pre-installing all the dependencies onto the relevant Perl images instead of having it done every job. In principle this too has worked fine, however when I attempted to delegate the image building to GitLab-CI as well I found out that Kaniko refuses to work with perl:5.14-threaded. From what I could tell the problem lies with the fact that the image in question uses schema 1 whereas Kaniko devs have decided to only support schema 2.

Would it be possible to have older Perl images on Docker Hub updated to schema 2? According to the discussion from https://github.com/GoogleContainerTools/kaniko/issues/509 all one has to do is pull such an image using a new-enough version of Docker and push it back to the Hub.

**Comment by zakame** [comment]
Hi @mkszuba, thanks for the report!

`perl:5.14-threaded` is rather old and thus is in schema 1 as it is no longer supported (meaning that it is no longer covered in [perlpolicy](https://metacpan.org/pod/distribution/perl/pod/perlpolicy.pod#MAINTENANCE-AND-SUPPORT) and thus no longer listed in [docker-library](https://github.com/docker-library/official-images/blob/master/library/perl) so it can be rebuilt periodically.)  I think you can just pull, retag and push to your own Docker Hub organization's repo as necessary:

```shell
docker pull perl:5.14-threaded
docker tag perl:5.14-threaded myorg/myperl:5.14-threaded
docker login
docker push myorg/myperl:5.14-threaded
```

Alternatively you can also rebuild `perl:5.14-threaded` from here, perhaps automating it using Gitlab-CI; you can probably glean some ideas on #68 for this.

**Comment by mkszuba** [comment]
OK. We have kept the possibility of rebuilding Perl images from scratch using your Dockerfiles as a fallback solution in the event of 5.14 images disappearing from Docker Hub - so I guess we will try that. Thanks for clarifying!

**Comment by zakame** [comment]
Yes, that should be a good call.  The `master` branch also no longer carries a bare `5.014.004-main,threaded` tag, as we now include the Debian codename so it becomes [`5.014.004-main,threaded-jessie`](https://github.com/Perl/docker-perl/blob/master/5.014.004-main%2Cthreaded-jessie/Dockerfile).
