### ISSUE TITLE
Cannot add modules in container

### ISSUE THREAD

**Issue by ricketyrocks** [Perl/docker-perl#71]
I cannot install modules when building a container. I have tried the official images and various OS images. I always hit this error.

```
Modification of a read-only value attempted at /usr/share/perl5/core_perl/CPAN/Distribution.pm line 4020.
```

**Comment by zakame** [comment]
Hi @ricketyrocks , thanks for the report!

Can you share more detail about what modules you're trying to install?  A (sanitized) `Dockerfile` would be really helpful so I can try to reproduce on my machine.

**Comment by zakame** [comment]
@ricketyrocks thanks, that's very helpful!  I can certainly reproduce your issue here.

Could you try this version:

```Dockerfile
FROM perl:5.30

RUN cpanm JSON Dancer2 File::Slurp Crypt::JWT URI DateTime LWP::UserAgent Data::UUID
```

I've omitted other modules (`POSIX`, `Sys::Hostname` et al.) as these are already part of the perl5 core.

**Comment by ricketyrocks** [comment]
Thanks! It looks like cpanm is the missing sauce to get modules installed.
