### ISSUE TITLE
No 5.30.1 tag for perl at hub.docker.com

### ISSUE THREAD

**Issue by elcamlost** [Perl/docker-perl#74]
There is no 5.30.1 tag but plain tags for all other versions from 5.28.0 to 5.30.0
Is it intended?

**Comment by zakame** [comment]
Thanks @elcamlost, there was a mistake in the previous tagging that's to be fixed in https://github.com/docker-library/official-images/pull/7023/commits/d57621357f947aeebd68c9057895d51d2c5f1a14

**Comment by elcamlost** [comment]
@zakame Thanks for such a robust answer ))
