### ISSUE TITLE
Unable to add Perl module WWW::Curl to Docker/Perl app

### ISSUE THREAD

**Issue by drjonasthomsen** [Perl/docker-perl#75]
I am trying to build a perl-app using the Docker image and the module WWW::Curl, but installation of WWW::Curl fails in this environment.
My Dockerfile is:
FROM perl:latest
RUN apt-get install -y \\
  libcurl4-openssl-dev \\
  libcurl4
RUN cpanm --verbose WWW::Curl::Easy

The error is:
The version is libcurl 7.64.0
Cannot find curl.h - cannot build constants files  - see Makefile.PL at Makefile.PL line 96.

**Comment by drjonasthomsen** [comment]
Backslahes are missing in the app-get install lines in the post. They are working in real life.

**Comment by tianon** [comment]
Given that `curl.h` exists in the `perl:latest` image as-is at `/usr/include/x86_64-linux-gnu/curl/curl.h` (without installing anything extra), I'd be inclined to think this is probably a bug with the `WWW::Curl::Easy` module.

That being said, https://github.com/szbalint/WWW--Curl/issues/18 / https://github.com/szbalint/WWW--Curl/pulls does not bode well for getting it fixed. :disappointed:

**Comment by zakame** [comment]
Hi @drjonasthomsen, thanks for the report; I can confirm and reproduce it myself.

It is as @tianon says, `WWW::Curl` is way out of date and can't be used on a newer libcurl; there's also a lot of build issues posted on [the RT queue](https://rt.cpan.org/Public/Dist/Display.html?Name=WWW-Curl).  I'd suggest using an alternative depending on your use cases, such as `HTTP::Tiny` or `Mojo::UserAgent`.

**Comment by zakame** [comment]
Let me close this as it is not strictly a docker-perl issue, it is more a CPAN module vs libcurl4 (curl 7.x) incompatibility.
