### ISSUE TITLE
FEATURE: Create Docker containters with updated core modules

### ISSUE THREAD

**Issue by rkleemann** [Perl/docker-perl#79]
There is a *long* list of modules that have a dual life in core and on CPAN, and having a Perl with all of those upgraded to the current stable version would ease and encourage upgrades.  Consider creating Docker container variants that already have all of the core modules upgraded to the latest equivalents on CPAN.

**Comment by zakame** [comment]
Hi @rkleemann, thanks for the suggestion!

I'd further suggest something along the lines of this:

```Dockerfile
FROM perl:latest

RUN cpanm App::cpanoutdated \
    && cpan-outdated -p | cpanm
```

Unfortunately doing this as a variant here will add some burden to official-image rebuilds (and to note, perl is among the [heavy hitters](https://github.com/docker-library/official-images/blob/master/heavy-hitters.txt) during periodic rebuilds.)  I'd instead encourage users/organizations to create derived images from `perl`, maintained through their own toolchain and/or CI, and installing updated core modules in those images (either via the `cpan-outdated` app above or through particular modules and updates tracked via `Carton`.)
