### ISSUE TITLE
[ support ] Where would PERL5LIB default on this image?

### ISSUE THREAD

**Issue by smonff** [Perl/docker-perl#81]
Hi,

I try to use this image in Gitlab-CI. I have this question about the default location of PERL5LIB if I don't set it by myself. I mean, if I do something like `cpanm Mojolicious`, will the modules install in `/usr/local/lib/perl5`?

Thanks.

**Comment by smonff** [comment]
Maybe the answer is *nowhere* because it is not set :/ ?

**Comment by skaji** [comment]
*  PERL5LIB is unset.
*  > if I do something like cpanm Mojolicious, will the modules install in /usr/local/lib/perl5?

    Yes.

**Comment by zakame** [comment]
HI @smonff !  Yes, @skaji is right, and to further the point, we also do not define/set any other [environment variables](https://metacpan.org/pod/perlrun#ENVIRONMENT) such as `PERL5OPT` either; we leave those to the discretion of the users of this image.

**Comment by smonff** [comment]
Thanks @skaji and @zakame.
