### ISSUE TITLE
/usr/bin/ld: cannot find -lperl

### ISSUE THREAD

**Issue by hstejas** [Perl/docker-perl#84]
I am trying to install Image:;Magick in the docker file 
I see that `libperl.so` is available here `/usr/local/lib/perl5/5.30.2/x86_64-linux-gnu/CORE/libperl.so`

```
FROM perl:5.30-slim-buster

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
    build-essential \
    libmagick++-dev && \
    cp /usr/include/x86_64-linux-gnu/ImageMagick-6/magick/magick-baseconfig.h /usr/include/ImageMagick-6/magick/

RUN find / -name libperl.so
RUN cpanm -v Image::Magick
```
But i get this error when linking

> chmod 644 "Magick.bs"
> "/usr/local/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Magick.bs blib/arch/auto/Image/Magick/Magick.bs 644
> "/usr/local/bin/perl" "/usr/local/lib/perl5/5.30.2/ExtUtils/xsubpp"  -typemap '/usr/local/lib/perl5/5.30.2/ExtUtils/typemap' -typemap '/root/.cpanm/work/1591346327.6/PerlMagick-6.89/typemap'  Magick.xs > Magick.xsc
> mv Magick.xsc Magick.c
> cc -c  -I/usr/local/include/ImageMagick-6 -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -I/usr/include/libxml2 -I"/usr/include/ImageMagick-6" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -I/usr/include/freetype2 -g -O2 -Wall -pthread -DMAGICKCORE_HDRI_ENABLE=0 -DMAGICKCORE_QUANTUM_DEPTH=16 -O2   -DVERSION=\"6.89\" -DXS_VERSION=\"6.89\" -fPIC "-I/usr/local/lib/perl5/5.30.2/x86_64-linux-gnu/CORE"  -D_LARGE_FILES=1 -DHAVE_CONFIG_H Magick.c
> rm -f blib/arch/auto/Image/Magick/Magick.so
> LD_RUN_PATH="/usr/lib/x86_64-linux-gnu" cc  -L/usr/local/lib -lMagickCore-6.Q16 -shared -O2 -L/usr/local/lib -fstack-protector-strong   Magick.o  -o blib/arch/auto/Image/Magick/Magick.so  \
>    -L/usr/local/lib -lMagickCore-6.Q16 -lperl -lm   \
>  
> /usr/bin/ld: cannot find -lperl

**Comment by skaji** [comment]
I don't think this is an issue for docker-perl.
See the last comment of https://rt.cpan.org/Public/Bug/Display.html?id=122253
> adds $Config{archlib}/CORE to $LIBS_magick

**Comment by Tekki** [comment]
There's a detailed explanation on perl.com: https://www.perl.com/article/57/2014/1/1/Shazam-Use-Image-Magick-with-Perlbrew-in-minutes/
docker-perl is compiled with the `-Duseshrplib` flag, so probably suceed if you install it from source (didn't try it yet).

**Comment by zakame** [comment]
Hi @hstejas, thanks for the report!

@skaji and @Tekki are right, you can probably make use of the [`PERL_MM_OPT`](https://metacpan.org/pod/ExtUtils::MakeMaker#PERL_MM_OPT) environment variable to set `CCFLAGS`/`LIBS` to the downstream `make`, and combine this with [`perl -V::archlib:`](https://perldoc.pl/perlrun#-V:configvar) magic to get the right path for `-lperl`, so something like 

```Dockerfile
ENV PERL_MM_OPT='LIBS="-L$(perl -V::archlib:)/CORE"'
RUN cpanm -v Image::Magick
```

Do expect failing tests, however (cf https://rt.cpan.org/Public/Bug/Display.html?id=113734) so I suggest using [Alien::ImageMagick](https://metacpan.org/pod/Alien::ImageMagick) instead.

**Comment by zakame** [comment]
If following the Alien::ImageMagick route and you're using 5.30, also be aware of [this issue](https://rt.cpan.org/Public/Bug/Display.html?id=130824)

**Comment by Tekki** [comment]
And by the way, there is an image [spleck/perlmagick7](https://hub.docker.com/r/spleck/perlmagick7) on Dockerhub, built by @spleck with ImageMagick 7.0.10-16 and updated on June 1, 2020.

**Comment by hstejas** [comment]
Thanks for the suggestions,
I tried Alien::ImageMagick and it installed without any issues, with cpanm and carton too.

But not i get this error. maybe its unrelated

st

> at("/home/container/local/lib/perl5/x86_64-linux-gnu-thread-multi/auto/HTTP/Parser/XS/XS.so", {st_mode=S_IFREG|0555, st_size=104128, ...}) = 0
> stat("/home/container/local/lib/perl5/x86_64-linux-gnu-thread-multi/auto/HTTP/Parser/XS/XS.bs", 0x5572d665c478) = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/home/container/local/lib/perl5/x86_64-linux-gnu-thread-multi/auto/HTTP/Parser/XS/XS.so", O_RDONLY|O_CLOEXEC) = 6
> read(6, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\23\0\0\0\0\0\0"..., 832) = 832
> fstat(6, {st_mode=S_IFREG|0555, st_size=104128, ...}) = 0
> mmap(NULL, 2113912, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 6, 0) = 0x7f2314152000
> mprotect(0x7f2314156000, 2093056, PROT_NONE) = 0
> mmap(0x7f2314355000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 6, 0x3000) = 0x7f2314355000
> close(6)                                = 0
> mprotect(0x7f2314355000, 4096, PROT_READ) = 0
> write(2, "XS.c: loadable library and perl "..., 104XS.c: loadable library and perl binaries are mismatched (got handshake key 0xde00080, needed 0xce00080
