### ISSUE TITLE
Install SOAP::Lite in perl container

### ISSUE THREAD

**Issue by kop57890** [Perl/docker-perl#87]
I want to install SOAP::Lite module in my perl container.
I'm using this Dockerfile below:

```
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN apt-get update
RUN apt-get install -y libdatetime-perl
RUN apt-get install -y libdbi-perl
RUN apt-get install -y libsoap-lite-perl
RUN apt-get install -y apache2*
RUN cpanm DBI
RUN cpanm DateTime
RUN cpanm SOAP::Lite
```
But I always got an message:

> Please tell me where I can find your apache src
>  [../apache_x.x/src] ../apache_x.x/src
> Can't stat `../apache_x.x/src'

How to give the correct path of apache in the Dockerfile?

**Comment by kop57890** [comment]
Correct Dockerfile content:

```
RUN cpan DBI
RUN cpan DateTime
RUN cpan SOAP::Lite
```

**Comment by zakame** [comment]
Hi @kop57890, thanks for the report!

You probably need the [`apache2-dev` package](https://packages.debian.org/buster/apache2-dev), something like this:

```Dockerfile
RUN apt-get update \
  && apt-get install -y --no-install-recommends \
     apache2-dev apache2 \
  && cpanm --notest --verbose SOAP::Lite DBI DateTime
```

On the other hand, `SOAP::Lite` doesn't have a direct dependency on Apache; may I ask why do you need Apache in the first place?

Also, you don't necessarily need the Debian packages for the CPAN modules if you going to install them through `cpan`/`cpanm` anyway.

**Comment by kop57890** [comment]
Hi @zakame
I try to use the command you suggested, and it works!!

```
FROM perl:latest
COPY . /usr/src/myapp
WORKDIR /usr/src/myapp
RUN cpanm --notest --verbose SOAP::Lite DBI DateTime
```

I googled a lot of document that how to install a perl module, and some of them just say install perl module by apt-get.
I am very appreciate for your kind help!

**Comment by zakame** [comment]
Glad to help @kop57890! :tada:
