### ISSUE TITLE
 Document DockerHub is incorrect

### ISSUE THREAD

**Issue by ryuichi1208** [Perl/docker-perl#98]
Document DockerHub is incorrect

https://hub.docker.com/_/perl/?tab=description&page=1&ordering=last_updated

There is an error in the description of Carton in this document.The path to copy is incorrect.

> Example: Creating a reusable Carton image for Perl projects

``` docekrfile
FROM perl:5.26

RUN cpanm Carton \
    && mkdir -p /usr/src/app
WORKDIR /usr/src/app

correct: ONBUILD COPY cpanfile* /usr/src/app
★ ONBUILD COPY cpanfile* /usr/src/myapp
ONBUILD RUN carton install

ONBUILD COPY . /usr/src/app
```

Isn't the copy destination of cpanfile "/usr/src/app" ?

**Comment by zakame** [comment]
Hi @ryuichi1208, nice catch!  Thanks for the heads-up.

The Hub documentation is on https://github.com/docker-library/docs/blob/master/perl/content.md, let me push a quick update :muscle:

**Comment by zakame** [comment]
This is now fixed, thanks @ryuichi1208 !
