### ISSUE TITLE
Not passing aws ecr scan

### ISSUE THREAD

**Issue by gita-v** [Perl/docker-perl#99]
Hi 😄 
Since the new image update, images are no longer passing amazon's ecr scan --
I am using `perl:5.32.1-slim-buster` in a blank Dockerfile and receive the following error ```UnsupportedImageError: The operating system and/or package manager are not supported.```
Previously it was working, do you know anything that has changed that could be causing this new issue?

**Comment by gita-v** [comment]
`
when attempting to scan an image that was built using an operating system that Amazon ECR doesn't support image scanning for
`
Is the pipeline for building the images changed recently? When I build the perl image myself locally and push to ecr it works fine, however using the one from docker-hub is giving the scan issue on Amazon.

**Comment by yosifkit** [comment]
Nothing has changed in the official-images build servers. It seems like the most recent build coincides with the last Debian image rebuild (https://github.com/docker-library/official-images/pull/9590).

```console
$ docker pull perl:5.32.1-slim-buster
5.32.1-slim-buster: Pulling from library/perl
45b42c59be33: Pull complete 
1e9377655695: Pull complete 
e5ced57e093d: Pull complete 
Digest: sha256:5bbf4ad3011c0757d087a1f401500d2291e1c8bc4f762177b0f0e065e0a167c4
Status: Downloaded newer image for perl:5.32.1-slim-buster
docker.io/library/perl:5.32.1-slim-buster
$ docker history perl:5.32.1-slim-buster 
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
c157f2b8b440        2 weeks ago         /bin/sh -c #(nop)  CMD ["perl5.32.1" "-de0"]    0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop) WORKDIR /                     0B                  
<missing>           2 weeks ago         /bin/sh -c apt-get update     && apt-get ins…   57.1MB              
<missing>           2 weeks ago         /bin/sh -c #(nop) WORKDIR /usr/src/perl         0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop) COPY file:3744c5cc39cdbdca…   0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  LABEL maintainer=Peter Ma…   0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop) ADD file:d5c41bfaf15180481…   69.2MB              


$ docker pull debian:buster-slim
buster-slim: Pulling from library/debian
45b42c59be33: Already exists 
Digest: sha256:13f0764262a064b2dd9f8a828bbaab29bdb1a1a0ac6adc8610a0a5f37e514955
Status: Downloaded newer image for debian:buster-slim
docker.io/library/debian:buster-slim
$ docker history debian:buster-slim
IMAGE               CREATED             CREATED BY                                      SIZE                COMMENT
cbd3a5bf0324        2 weeks ago         /bin/sh -c #(nop)  CMD ["bash"]                 0B                  
<missing>           2 weeks ago         /bin/sh -c #(nop) ADD file:d5c41bfaf15180481…   69.2MB              
```

**Comment by gita-v** [comment]
Ahhh you are right, if I rebuild with `debian:buster-20210111-slim` then it works -- thank you 😄

**Comment by gita-v** [comment]
Anway to get a perl image with the older working debian buster? or should I get it out from their end to fix the issue?

**Comment by zakame** [comment]
Hey @gita-v @yosifkit , thanks for the updates!

I think you can still pull `debian:10.7-slim` and tag it locally as `debian:buster-slim` so you can rebuild your own `perl:5.32.1-slim-buster` image as needed, at least until AWS ECR gets updated for 10.8.
